version: '3.9'


services:
  db:
    image: postgres:14.6
    container_name: welbex_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - config/.env
    expose:
      - "5432"
  welbex_web:
    build:
      dockerfile: Dockerfile
      context: .
    image: welbex_docker:latest
    container_name: welbex-rest
    command: >
      bash -c "./manage.py migrate && ./manage.py add_locations && ./manage.py add_cars && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/welbex_project/static
      - media_volume:/welbex_project/media
      - .:/welbex_project
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    depends_on:
      - db
  redis:
    image: redis:6.0.17
    container_name: welbex_redis
  celery:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: welbex_celery
    command: celery -A config worker -l info
    volumes:
      - ./:/welbex_project
    env_file:
      - config/.env
    depends_on:
      - redis
      - welbex_web
      - db
  celery-beat:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: welbex_celery_beat
    command: celery -A config beat -l info
    volumes:
      - ./:/welbex_project
    env_file:
      - config/.env
    depends_on:
      - redis
      - welbex_web
      - db


volumes:
  static_volume:
  media_volume:
  postgres_data: