# Generated by Django 4.2.1 on 2023-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='load_capacity',
            field=models.FloatField(default=985),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=65),
        ),
    ]
