# Generated by Django 4.2.1 on 2023-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0003_alter_car_load_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='uid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
