# Generated by Django 4.2.1 on 2023-05-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_service', '0005_alter_cargo_delivery_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
